services:
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - 4000:4000
    depends_on:
      - mongo
    stdin_open: true
    networks:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  nginx:
    image: nginx:1.25.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - backend
    networks:
      - mongo
networks:
  mongo:
